### ISSUE TITLE
请问 vless 协议增加了用户之后，如何在clash的yaml配置文件里写呢？

### ISSUE THREAD

**Issue by rockyzhz** [FranzKafkaYu/x-ui#506]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

我用的是最新版的openclash，它的配置文件里我现在不知道怎么填，填uuid的话，连不上去。
填email的话，openclash无法启动。

```yaml
  - name: "vless-ws"
    type: vless
    server: for.example.com
    port: 443
    uuid: d58624ca-c270-4c8b-b0b4-e0270184ce66
#    email: dmgw.love@xray.com
    udp: true
    tls: true
    network: ws
    servername: for.example.com # priority over wss host
    skip-cert-verify: true
    ws-opts:
      path: "/youneedguess2"
      headers:
        Host: for.example.com
```

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by rockyzhz** [comment]
我另外按照 [Wiki][1] 里的节点配置，分别配置了两个类型的节点：
1. Vless+tls+xtls-rprx-vison
2. Vless+reality+tcp+xtls-rprx-vison

clash的yaml配置写法按照 [Clash.Meta][2] 的范例 [config.yaml][3]，用下面这段配置：
```yaml
  - name: "vless-vision"
    type: vless
    server: server
    port: 443
    uuid: uuid
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    # fingerprint: xxxx
    # skip-cert-verify: true

  - name: "vless-reality-vision"
    type: vless
    server: server
    port: 443
    uuid: uuid
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.microsoft.com # REALITY servername
    reality-opts:
      public-key: xxx
      short-id: xxx # optional
    client-fingerprint: chrome # cannot be empty
```

始终是无法工作，可以帮忙指正一下吗？

[1]:https://github.com/FranzKafkaYu/x-ui/wiki/%E8%8A%82%E7%82%B9%E9%85%8D%E7%BD%AE
[2]:https://github.com/MetaCubeX/Clash.Meta/tree/Alpha
[3]:https://github.com/MetaCubeX/Clash.Meta/raw/Alpha/docs/config.yaml
